[{"cod_curso":"Agronomia"},
{"cod_curso":"Ciências Econômicas"},
{"cod_curso":"Administração"},
{"cod_curso":"Economia Doméstica"},
{"cod_curso":"Educação Física"},
{"cod_curso":"Ciências Biológicas"},
{"cod_curso":"Física"},
{"cod_curso":"Matemática"},
{"cod_curso":"Engenharia Química"},
{"cod_curso":"Química"},
{"cod_curso":"Engenharia de Alimentos"},
{"cod_curso":"Engenharia Agrícola"},
{"cod_curso":"Engenharia de Agrimensura"},
{"cod_curso":"Arquitetura e Urbanismo"},
{"cod_curso":"História"},
{"cod_curso":"Pedagogia"},
{"cod_curso":"Letras - Português / Literatura"},
{"cod_curso":"Letras - Port. / Inglês / Lit."},
{"cod_curso":"Engenharia Florestal"},
{"cod_curso":"Filosofia"},
{"cod_curso":"Geografia"},
{"cod_curso":"Direito"},
{"cod_curso":"Ciências Sociais"},
{"cod_curso":"Belas Artes"},
{"cod_curso":"Engenharia de Materiais"},
{"cod_curso":"Farmácia"},
{"cod_curso":"Psicologia"},
{"cod_curso":"Sistemas de Informação"},
{"cod_curso":"Geologia"},
{"cod_curso":"Administração Pública"},
{"cod_curso":"Ciências Contábeis"},
{"cod_curso":"Comunicação Social - Jornalismo"},
{"cod_curso":"Hotelaria"},
{"cod_curso":"Relações Internacionais"},
{"cod_curso":"Gestão Ambiental"},
{"cod_curso":"Medicina Veterinária"},
{"cod_curso":"Zootecnia"},
{"cod_curso":"Turismo"},
{"cod_curso":"Letras - Português/literaturas"},
{"cod_curso":"Letras - Port. / Espanhol / Lit."},
{"cod_curso":"Ciência da Computação"},
{"cod_curso":"Ciências Agrícolas"}
]